import { type CSSProperties, useState } from 'react';
import { ChevronDown, Fingerprint, ArrowUpRight } from 'lucide-react';
import type { Entry } from './data';

/** A waterfall of the existing engine's factors. Does not recompute priority. */
export function ScoreBreakdown({entry,onOpen}:{entry:Entry|null;onOpen?:()=>void}){
 const [expanded,setExpanded]=useState<number|null>(null);
 const factors=entry?.score.factores??[];
 let accumulated=0;
 const rows=factors.map(f=>{const start=accumulated;accumulated+=f.puntos;return {...f,start,end:accumulated};});
 const min=Math.min(0,...rows.map(r=>Math.min(r.start,r.end)));
 const max=Math.max(160,entry?.score_interno??0,...rows.map(r=>Math.max(r.start,r.end)))*1.06;
 const position=(n:number)=>(n-min)/(max-min)*100;
 const partial=entry&&Math.abs(Math.max(0,accumulated)-entry.score_interno)>.01;
 return <section className={'score-lab '+(entry?'has-score':'awaiting-score')} data-priority={entry?severity(entry.prioridad):undefined} aria-label="Desglose del VulnSOC Score">
  <header className="score-lab-header"><div><span className="eyebrow">MOTOR DE PRIORIZACIÓN CONTEXTUAL</span><h2>Cómo se construye la prioridad</h2></div>{onOpen&&entry&&<button className="text-link mono" onClick={onOpen}>{entry.cve_id}<ArrowUpRight size={14}/></button>}</header>
  <div className="score-lab-layout"><div className="score-verdict"><span className="verdict-label">RESULTADO CONTEXTUAL</span><span>Score interno</span><div className="internal-number">{entry?entry.score_interno:'—'}<small>pts</small></div>{entry?<span className={'badge '+severity(entry.prioridad)}><i/>{entry.prioridad}</span>:<span className="neutral-badge">Pendiente de análisis</span>}<div className="visible-score"><svg className="score-orbit" viewBox="0 0 100 100" aria-hidden="true"><circle className="orbit-track" cx="50" cy="50" r="44"/><circle className="orbit-value" cx="50" cy="50" r="44" pathLength="100" strokeDasharray={`${Math.max(0,Math.min(100,entry?.score_mostrado??0))} 100`}/></svg><span>VulnSOC Score<small>Escala visible · 0–100</small></span><b>{entry?entry.score_mostrado:'—'}<small>/100</small></b></div><p>El score interno ordena las vulnerabilidades. El valor visible se limita a 100.</p><div className="threshold-legend"><span>BAJA <b>&lt;55</b></span><span>MEDIA <b>55–89</b></span><span>ALTA <b>90–129</b></span><span>CRÍTICA <b>≥130</b></span></div></div>
  <div className="score-waterfall">{entry&&rows.length?<><div className="waterfall-heading"><span>01 / EVIDENCIAS QUE SUMAN CONTEXTO</span><span>Σ PUNTOS</span></div><div className="waterfall-rows">{rows.map((r,i)=><div key={i} style={{'--step':Math.min(i,12)} as CSSProperties} className={'waterfall-item '+(expanded===i?'expanded':'')}><button className="waterfall-row" onClick={()=>setExpanded(expanded===i?null:i)} aria-expanded={expanded===i} aria-controls={`factor-${entry.cve_id}-${i}`}><span className="factor-name"><span className="factor-step">{String(i+1).padStart(2,'0')}</span>{r.factor}<small className={r.puntos<0?'negative':''}>{r.puntos>0?'+':''}{r.puntos} pts</small></span><span className="waterfall-track" aria-hidden="true"><i className={'waterfall-bar '+(r.puntos<0?'deduction':r.puntos===0?'zero':'')} style={{left:`${position(Math.min(r.start,r.end))}%`,width:r.puntos===0?'2px':`${Math.abs(r.puntos)/(max-min)*100}%`}}/><i className="waterfall-end" style={{left:`${position(r.end)}%`}}/></span><b className="accumulated-value">{r.end}</b><ChevronDown size={13}/></button><div id={`factor-${entry.cve_id}-${i}`} hidden={expanded!==i} className="factor-explanation">{r.detalle}</div></div>)}</div><div className="score-axis"><span>{min}</span><span>Aportaciones acumuladas · puntos, no porcentajes</span><span>{Math.round(max)}</span></div>{partial&&<p className="help">Desglose parcial: los factores disponibles suman {accumulated} puntos; el informe registra {entry.score_interno}. Se conserva el resultado original.</p>}<div className="score-resolution"><span><small>02 / SCORE INTERNO</small><b>{entry.score_interno} pts</b></span><ArrowUpRight size={18}/><span><small>03 / PRIORIDAD</small><b className="resolution-priority" data-priority={severity(entry.prioridad)}>{entry.prioridad}</b></span><ArrowUpRight size={18}/><span><small>04 / ESCALA VISIBLE</small><b>{entry.score_mostrado}<em>/100</em></b></span></div><p className="score-hint">Selecciona un factor para consultar su evidencia. Los ajustes negativos reducen la prioridad.</p></>:<div className="score-empty"><Fingerprint size={28}/><h3>Cada punto debe tener una razón.</h3><p>Al analizar un CVE verás cuánto aportan CVSS, explotación, recencia, vector y contexto de activos. Selecciona cada factor para consultar la evidencia que lo respalda.</p></div>}</div></div>
 </section>;
}
export function severity(priority:string){return priority==='CRÍTICA'?'critical':priority==='ALTA'?'high':priority==='MEDIA'?'medium':'low';}
